---
sudo: false
language: python
cache: pip
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.5"

install:
  - pip install -r ./requirements.txt
  - pip install -r ./requirements_test.txt
  - pip install coveralls
python:
  - "3.6"

before_script:
  - psql -c 'create role solo with superuser login;' -U postgres
  - psql -c 'create database solo with owner solo;' -U postgres

# --source specifies what packages to cover, you probably want to use that option
script:
    - py.test

after_success: coveralls