---
sudo: false
language: python
cache: pip
install:
  - pip install --user -r ./requirements.txt
  - pip install --user -r ./requirements_test.txt
  - pip install coveralls
python:
  - "3.5"

# --source specifies what packages to cover, you probably want to use that option
script:
    coverage run --source=solo py.test

after_success: coveralls