---
dist: xenial
sudo: true
language: python
cache: pip
services:
  - docker
# addons:
#   postgresql: "9.4"

install:
  - pip install -r ./requirements/minimal.txt
  - pip install -r ./requirements/test.txt
  - pip install coveralls
python:
  - "3.7"

# before_script:
#   - psql -c 'create role solo with superuser login;' -U postgres
#   - psql -c 'create database solo with owner solo;' -U postgres

# --source specifies what packages to cover, you probably want to use that option
script:
    - py.test

after_success: coveralls
