version: "2"
services:
  postgres:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_USER: solo
      POSTGRES_PASSWORD: solo
      POSTGRES_DB: solo
    ports:
      - 5432:5432

  redis:
    image: redis:5.0-rc5-alpine
    ports:
      - 6379:6379
