"""init

Revision ID: solo.apps.accounts:initial
Revises: 
Create Date: 2016-05-16 10:08:09.641443

"""

# revision identifiers, used by Alembic.
revision = 'solo.apps.accounts:initial'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    from solo.server.db.types import PythonMappedEnum
    from solo.apps.auth.models import AuthProvider
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE
        TYPE
        auth_provider
        AS
        ENUM('github');
    """)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=140), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', PythonMappedEnum(AuthProvider, name='auth_provider'), nullable=False),
    sa.Column('provider_uid', sa.Unicode(length=140), server_default='', nullable=False),
    sa.Column('access_token', sa.Unicode(length=140), server_default='', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_uid', name='uniq_provider_provider_uid')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth')
    op.drop_table('auth')
    op.drop_table('users')
    ### end Alembic commands ###
