"""initial

Revision ID: solo.apps.accounts:initial
Revises: 
Create Date: 2016-05-16 10:08:09.641443

"""

# revision identifiers, used by Alembic.
revision = 'solo.apps.accounts:initial'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=140), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
