#%RAML 0.8
# specs at https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md
title: Solo Accounts API
version: 1.0
mediaType: application/json
baseUri: https://{host}/{appPrefix}
baseUriParameters:
  host:
    description: Project host
  appPrefix:
    description: Application URL prefix
protocols:
  - HTTPS

/login:
  /{provider:<solo.apps.accounts.model:AuthProvider>}:
    post:
      description: Initiate authentication flow on backend

    /callback:
      get:
        description: Callback handler on backend


/users:
  get:
    description: List registered accounts

  /me:
    get:
      description: Current session's account details. Can be used to authenticate and authorize frontend client after authenticated backend.

  /{userId}:
    get:
      description: Get account details
    post:
      description: Update account details
    delete:
      description: Delete account
