---
# Develop playbook for a local vagrant instance
- hosts: develop
  become: yes
  become_method: sudo
  roles:
    - role: postgresql
      postgresql_listen_addresses: "*"
      postgresql_databases:
        - "{{ project_name }}"

    - role: DavidWittman.redis
      redis_version: 3.0.7
      redis_verify_checksum: true
      redis_checksum: "sha1:e56b4b7e033ae8dbf311f9191cf6fdf3ae974d1c"
      redis_bind: 0.0.0.0
      redis_port: 6379
      redis_password: false
      redis_tcp_backlog: 511
      redis_tcp_keepalive: 0
      # Max connected clients at a time
      redis_maxclients: 10000
      redis_timeout: 0
      # Socket options
      # Set socket_path to the desired path to the socket. E.g. /var/run/redis/{{ redis_port }}.sock
      redis_socket_path: false
      redis_socket_perm: 755

      ## Replication options
      # Set slaveof just as you would in redis.conf. (e.g. "redis01 6379")
      redis_slaveof: false
      # Make slaves read-only. "yes" or "no"
      redis_slave_read_only: "yes"
      redis_slave_priority: 100
      redis_repl_backlog_size: false

      ## Logging
      redis_logfile: '""'
      # Enable syslog. "yes" or "no"
      redis_syslog_enabled: "yes"
      redis_syslog_ident: redis_{{ redis_port }}
      # Syslog facility. Must be USER or LOCAL0-LOCAL7
      redis_syslog_facility: USER

      ## General configuration
      redis_daemonize: "yes"
      redis_pidfile: /var/run/redis/{{ redis_port }}.pid
      # Number of databases to allow
      redis_databases: 16
      redis_loglevel: notice
      # Log queries slower than this many milliseconds. -1 to disable
      redis_slowlog_log_slower_than: 10000
      # Maximum number of slow queries to save
      redis_slowlog_max_len: 128
      # Redis memory limit (e.g. 4294967296, 4096mb, 4gb)
      redis_maxmemory: false
      redis_maxmemory_policy: noeviction
      redis_rename_commands: []
      # How frequently to snapshot the database to disk
      # e.g. "900 1" => 900 seconds if at least 1 key changed
      redis_save:
        - 900 1
        - 300 10
        - 60 10000
      redis_appendonly: "no"
      redis_appendfilename: "appendonly.aof"
      redis_appendfsync: "everysec"
      redis_no_appendfsync_on_rewrite: "no"
      redis_auto_aof_rewrite_percentage: "100"
      redis_auto_aof_rewrite_min_size: "64mb"

      ## Redis sentinel configs
      # Set this to true on a host to configure it as a Sentinel
      redis_sentinel: false

    - role: site

  # pre_tasks are executed before roles
  pre_tasks:
    - include: includes/remote_host_prerequisites.yml